version: '3.8'

services:
  nodeodm:
    image: opendronemap/nodeodm:latest
    container_name: powerscan_nodeodm
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - nodeodm_data:/var/www/data

volumes:
  nodeodm_data:
